- name: Clone repo, build, push, and run Docker container on remote EC2 instance
  hosts: docker_host
  become: true
  vars:
    github_repo: "https://github.com/shubhamdhole97/nodejs.git"
    clone_path: "/home/ubuntu/nodejsapplication"
    image_name: shubhamdhole97/nodejs
    image_tag: latest
    container_name: nodejscontainer

  tasks:
    - name: Load secrets from Vault
      ansible.builtin.include_vars:
        file: secrets.yml
        name: secrets

    - name: Install Git (if not installed)
      package:
        name: git
        state: present

    - name: Clone GitHub repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ clone_path }}"
        version: main
        force: yes

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ secrets.dockerhub_username }}"
        password: "{{ secrets.dockerhub_password }}"
      no_log: true  # Hides sensitive output

    - name: Build Docker image from cloned repository
      docker_image:
        source: build
        build:
          path: "{{ clone_path }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: no
      register: build_result

    - name: Push Docker image to Docker Hub
      command: docker push {{ image_name }}:{{ image_tag }}

    - name: Stop existing container (if any)
      docker_container:
        name: "{{ container_name }}"
        state: stopped
        force_kill: true
      ignore_errors: yes

    - name: Remove existing container (if any)
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Run the container from the new image
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
