---
- name: Clone repo, build, push, and run Docker container on remote EC2 instance
  hosts: docker_host
  become: true
  vars:
    github_repo: "https://github.com/shubhamdhole97/nodejs.git"
    clone_path: "/home/ubuntu/nodejs"
    image_name: "shubhamdhole97/imagenavbanvla"
    image_tag: "latest"
    container_name: "containernameahe"
    dockerhub_username: "shubhamdhole97"
    dockerhub_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      ... # Encrypted password here

  tasks:
    - name: Install required packages
      package:
        name: git
        state: present

    - name: Clone GitHub repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ clone_path }}"
        version: main
        force: yes

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      retries: 3
      delay: 10

    - name: Build Docker image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ clone_path }}"
        push: no
      register: build_result

    - name: Push Docker image to Docker Hub
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
      when: build_result.changed

    - name: Stop existing container (if running)
      docker_container:
        name: "{{ container_name }}"
        state: stopped
        force_kill: true
      ignore_errors: yes

    - name: Remove existing container (if any)
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Run the container from the new image
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
